/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.com.mycompany.sistema_farmacia.gui;

/**
 *
 * @author LENOVO
 */
public class Panel_Tipo_Movimiento extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Tipo_Movimiento
     */
    public Panel_Tipo_Movimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Movimiento_Fondo = new javax.swing.JPanel();
        Texto_Tipo_Movimiento = new javax.swing.JLabel();
        RadioButton_Venta = new javax.swing.JRadioButton();
        RadioButton_Venta1 = new javax.swing.JRadioButton();
        RadioButton_Venta2 = new javax.swing.JRadioButton();
        Boton_Salir_Movimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Movimiento_Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Movimiento_Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_Tipo_Movimiento.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        Texto_Tipo_Movimiento.setText("Elegir Tipo de Movimiento");
        Movimiento_Fondo.add(Texto_Tipo_Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        RadioButton_Venta.setBackground(new java.awt.Color(204, 204, 204));
        RadioButton_Venta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RadioButton_Venta.setText("Cancelar Compra");
        RadioButton_Venta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RadioButton_Venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RadioButton_Venta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Movimiento_Fondo.add(RadioButton_Venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 160, 30));

        RadioButton_Venta1.setBackground(new java.awt.Color(204, 204, 204));
        RadioButton_Venta1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RadioButton_Venta1.setText("Venta");
        RadioButton_Venta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RadioButton_Venta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RadioButton_Venta1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Movimiento_Fondo.add(RadioButton_Venta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, 30));

        RadioButton_Venta2.setBackground(new java.awt.Color(204, 204, 204));
        RadioButton_Venta2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RadioButton_Venta2.setText("Detalle de Compra");
        RadioButton_Venta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RadioButton_Venta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RadioButton_Venta2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        RadioButton_Venta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_Venta2ActionPerformed(evt);
            }
        });
        Movimiento_Fondo.add(RadioButton_Venta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 160, 30));

        Boton_Salir_Movimiento.setBackground(new java.awt.Color(255, 51, 51));
        Boton_Salir_Movimiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Boton_Salir_Movimiento.setText("Salir");
        Movimiento_Fondo.add(Boton_Salir_Movimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Movimiento_Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Movimiento_Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioButton_Venta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_Venta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_Venta2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Tipo_Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Tipo_Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Tipo_Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Tipo_Movimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Tipo_Movimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Salir_Movimiento;
    private javax.swing.JPanel Movimiento_Fondo;
    private javax.swing.JRadioButton RadioButton_Venta;
    private javax.swing.JRadioButton RadioButton_Venta1;
    private javax.swing.JRadioButton RadioButton_Venta2;
    private javax.swing.JLabel Texto_Tipo_Movimiento;
    // End of variables declaration//GEN-END:variables
}
